# Generated by Django 5.1.4 on 2026-07-17 02:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('super_admin', 'Super Administrator'), ('company_secretary', 'Company Secretary'), ('chairman', 'Chairman'), ('executive_director', 'Executive Director'), ('non_executive_director', 'Non-Executive Director'), ('independent_director', 'Independent Director'), ('committee_member', 'Committee Member'), ('presenter', 'Presenter/Invitee'), ('auditor', 'Auditor'), ('legal_counsel', 'Legal Counsel'), ('portal_admin', 'Portal Administrator')], max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('entity', models.ForeignKey(blank=True, help_text='Null = group-level role', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='role_assignments', to='entities.entity')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'role', 'entity')},
            },
        ),
    ]
