# Generated by Django 5.1.4 on 2026-07-17 03:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resolutions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='resolution',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resolution',
            name='threshold',
            field=models.PositiveIntegerField(default=0, help_text='Signatures required (circular)'),
        ),
        migrations.CreateModel(
            name='Signature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate', models.CharField(max_length=512)),
                ('signed_at', models.DateTimeField(auto_now_add=True)),
                ('resolution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signatures', to='resolutions.resolution')),
                ('signer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('resolution', 'signer')},
            },
        ),
    ]
