# Generated by Django 5.1.4 on 2026-07-17 03:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resolutions', '0002_resolution_expires_at_resolution_threshold_signature'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CertifiedTrueCopy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=80)),
                ('body', models.TextField()),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('resolution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ctcs', to='resolutions.resolution')),
            ],
        ),
    ]
