# Generated by Django 5.1.4 on 2026-07-17 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resolutions', '0003_certifiedtruecopy'),
    ]

    operations = [
        migrations.AddField(
            model_name='resolution',
            name='voting_mode',
            field=models.CharField(choices=[('open', 'Open (show of hands)'), ('secret', 'Secret ballot'), ('poll', 'Poll (weighted)')], default='open', max_length=16),
        ),
        migrations.AddField(
            model_name='vote',
            name='weight',
            field=models.PositiveIntegerField(default=1, help_text='Voting weight for poll mode (e.g. shares)'),
        ),
    ]
