# Generated by Django 5.1.4 on 2026-07-17 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0004_meeting_quorum_attendance'),
        ('resolutions', '0004_resolution_voting_mode_vote_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='resolution',
            name='agenda_item',
            field=models.ForeignKey(blank=True, help_text='The item this motion belongs to — used for item-level recusal in voting', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolutions', to='meetings.agendaitem'),
        ),
    ]
