# Generated by Django 5.1.4 on 2026-07-17 23:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0003_entitysettings'),
        ('resolutions', '0005_resolution_agenda_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='resolution',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Monetary value of the decision, validated against the DoA matrix', max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='resolution',
            name='category',
            field=models.CharField(blank=True, default='', help_text='DoA category, e.g. Capital expenditure', max_length=64),
        ),
        migrations.AddField(
            model_name='resolution',
            name='resolution_class',
            field=models.CharField(choices=[('ordinary', 'Ordinary (simple majority)'), ('special', 'Special (≥75%)')], default='ordinary', help_text='Special resolutions require the statutory 75% threshold (CAMA)', max_length=16),
        ),
        migrations.CreateModel(
            name='DelegationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(help_text='e.g. Capital expenditure, Disposals, Contracts', max_length=64)),
                ('approver', models.CharField(help_text='e.g. Managing Director, Board Risk Committee, Full Board', max_length=128)),
                ('max_amount', models.DecimalField(decimal_places=2, help_text='Authority limit (NGN)', max_digits=18)),
                ('tier', models.PositiveIntegerField(default=1, help_text='Escalation order; higher = more authority')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delegation_rules', to='entities.entity')),
            ],
            options={
                'ordering': ('entity__legal_name', 'category', 'tier'),
                'unique_together': {('entity', 'category', 'tier')},
            },
        ),
    ]
