# Generated by Django 5.1.4 on 2026-07-17 20:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entities', '0003_entitysettings'),
        ('meetings', '0004_meeting_quorum_attendance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Committee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('charter', models.TextField(blank=True, default='', help_text='Terms of reference')),
                ('charter_adopted_on', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='committees', to='entities.entity')),
            ],
            options={
                'ordering': ('entity__legal_name', 'name'),
                'unique_together': {('entity', 'name')},
            },
        ),
        migrations.CreateModel(
            name='CommitteeMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('chair', 'Chair'), ('member', 'Member')], default='member', max_length=12)),
                ('term_start', models.DateField()),
                ('term_end', models.DateField(blank=True, help_text='Rotation date; null = open-ended', null=True)),
                ('ended_on', models.DateField(blank=True, help_text='Actual end (resignation/rotation)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('committee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='committees.committee')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='committee_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-role', 'term_start'),
            },
        ),
        migrations.CreateModel(
            name='CommitteeReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('summary', models.TextField()),
                ('status', models.CharField(choices=[('submitted', 'Submitted to board'), ('noted', 'Noted by the board')], default='submitted', max_length=12)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('noted_at', models.DateTimeField(blank=True, null=True)),
                ('committee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='committees.committee')),
                ('meeting', models.ForeignKey(blank=True, help_text='The board meeting this report goes to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='committee_reports', to='meetings.meeting')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-submitted_at',),
            },
        ),
    ]
