# Generated by Django 5.1.4 on 2026-07-17 03:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entities', '0002_entity_code'),
        ('meetings', '0004_meeting_quorum_attendance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('owner_name', models.CharField(blank=True, default='', help_text='For non-member owners', max_length=255)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('done', 'Done')], default='open', max_length=8)),
                ('evidence', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agenda_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions', to='meetings.agendaitem')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='entities.entity')),
                ('meeting', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions', to='meetings.meeting')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('due_date', 'id'),
            },
        ),
    ]
