# Generated by Django 5.1.4 on 2026-07-17 02:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('meeting_type', models.CharField(choices=[('board', 'Board'), ('committee', 'Committee'), ('agm', 'AGM'), ('egm', 'EGM')], default='board', max_length=16)),
                ('starts_at', models.DateTimeField()),
                ('timezone', models.CharField(default='Africa/Lagos', max_length=64)),
                ('location', models.CharField(blank=True, default='', max_length=255)),
                ('is_virtual', models.BooleanField(default=False)),
                ('virtual_link', models.URLField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='entities.entity')),
            ],
            options={
                'ordering': ('starts_at',),
            },
        ),
    ]
