# Generated by Django 5.1.4 on 2026-07-17 02:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0002_consenttoshortnotice'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgendaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('item_type', models.CharField(choices=[('approval', 'For Approval'), ('discussion', 'For Discussion'), ('noting', 'For Noting')], default='discussion', max_length=16)),
                ('time_allocation_minutes', models.PositiveIntegerField(default=0)),
                ('position', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agenda_items', to='meetings.meeting')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_agenda_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('position', 'id'),
            },
        ),
    ]
