# Generated by Django 5.1.4 on 2026-07-17 02:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0003_agendaitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='quorum',
            field=models.PositiveIntegerField(default=0, help_text='Minimum present for a valid meeting'),
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('physical', 'Physical'), ('virtual', 'Virtual'), ('proxy', 'Proxy')], default='physical', max_length=16)),
                ('status', models.CharField(choices=[('present', 'Present'), ('apology', 'Apology'), ('absent', 'Absent')], default='present', max_length=16)),
                ('recorded_at', models.DateTimeField(auto_now=True)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='meetings.meeting')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to=settings.AUTH_USER_MODEL)),
                ('proxy_for', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proxies_held', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('meeting', 'member')},
            },
        ),
    ]
