# Generated by Django 5.1.4 on 2026-07-17 20:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entities', '0003_entitysettings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplianceObligation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('regulator', models.CharField(help_text='CAC, CBN, FIRS, NDPC…', max_length=64)),
                ('frequency', models.CharField(choices=[('annual', 'Annual'), ('quarterly', 'Quarterly'), ('monthly', 'Monthly'), ('once', 'One-off')], default='annual', max_length=12)),
                ('due_date', models.DateField(help_text='Next due date; rolls forward on filing')),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='obligations', to='entities.entity')),
            ],
            options={
                'ordering': ('due_date',),
            },
        ),
        migrations.CreateModel(
            name='Filing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_label', models.CharField(help_text='e.g. FY2025, Q2 2026', max_length=64)),
                ('filed_on', models.DateField()),
                ('evidence', models.CharField(blank=True, default='', help_text='Receipt no., acknowledgement ref., or document link', max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('filed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('obligation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filings', to='compliance.complianceobligation')),
            ],
            options={
                'ordering': ('-filed_on',),
            },
        ),
    ]
