# Generated by Django 5.1.4 on 2026-07-17 03:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('meetings', '0004_meeting_quorum_attendance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MinuteBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, default='')),
                ('agenda_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='minute_blocks', to='meetings.agendaitem')),
            ],
            options={
                'ordering': ('agenda_item__position',),
            },
        ),
        migrations.CreateModel(
            name='InlineDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('action', 'Action'), ('resolution', 'Resolution')], max_length=16)),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inline_decisions', to='minutes.minuteblock')),
            ],
        ),
        migrations.CreateModel(
            name='Minutes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('draft', 'Draft'), ('chairman_review', 'Chairman review'), ('circulated', 'Circulated for comment'), ('adopted', 'Adopted'), ('signed', 'Signed')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attendees', models.ManyToManyField(blank=True, related_name='minutes_present', to=settings.AUTH_USER_MODEL)),
                ('meeting', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='minutes', to='meetings.meeting')),
            ],
            options={
                'verbose_name_plural': 'minutes',
            },
        ),
        migrations.AddField(
            model_name='minuteblock',
            name='minutes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='minutes.minutes'),
        ),
        migrations.AlterUniqueTogether(
            name='minuteblock',
            unique_together={('minutes', 'agenda_item')},
        ),
    ]
