# Generated by Django 5.1.4 on 2026-07-17 01:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legal_name', models.CharField(max_length=255)),
                ('cac_rc_number', models.CharField(blank=True, default='', max_length=32, verbose_name='CAC RC number')),
                ('incorporation_date', models.DateField(blank=True, null=True)),
                ('registered_address', models.TextField(blank=True, default='')),
                ('share_capital', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('financial_year_end', models.CharField(blank=True, default='', help_text='MM-DD', max_length=5)),
                ('company_secretary', models.CharField(blank=True, default='', max_length=255)),
                ('auditors', models.CharField(blank=True, default='', max_length=255)),
                ('regulators', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='entities.entity')),
            ],
            options={
                'verbose_name_plural': 'entities',
                'ordering': ('legal_name',),
            },
        ),
    ]
