# Generated by Django 5.1.4 on 2026-07-17 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='code',
            field=models.CharField(blank=True, default='', help_text='Short code for numbering, e.g. CNI', max_length=8),
        ),
    ]
