# Generated by Django 5.1.4 on 2026-07-17 03:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0002_entity_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntitySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_primary_color', models.CharField(default='#2563EB', max_length=9)),
                ('logo_url', models.CharField(blank=True, default='', max_length=512)),
                ('resolution_number_format', models.CharField(default='{code}/{body}/{year}/{seq}', max_length=64)),
                ('retention_days', models.PositiveIntegerField(default=0, help_text='0 = retain indefinitely')),
                ('notification_policy', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='entities.entity')),
            ],
            options={
                'verbose_name_plural': 'entity settings',
            },
        ),
    ]
