# Generated by Django 5.1.4 on 2026-07-17 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='access_mode',
            field=models.CharField(choices=[('view_only', 'View only'), ('downloadable', 'Downloadable')], default='view_only', max_length=16),
        ),
    ]
