# Generated by Django 5.1.4 on 2026-07-18 23:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_document_agenda_item_document_is_late_and_more'),
        ('meetings', '0004_meeting_quorum_attendance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='legal_hold',
            field=models.BooleanField(default=False, help_text='Under legal hold — purge is blocked regardless of retention'),
        ),
        migrations.AddField(
            model_name='document',
            name='purged',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='document',
            name='purged_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='retention_until',
            field=models.DateField(blank=True, help_text='End of retention; eligible for purge after this date', null=True),
        ),
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.PositiveIntegerField(default=1)),
                ('text', models.TextField()),
                ('visibility', models.CharField(choices=[('private', 'Private'), ('shared', 'Shared with named recipients')], default='private', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to='documents.document')),
                ('shared_with', models.ManyToManyField(blank=True, related_name='shared_annotations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('page', 'created_at'),
            },
        ),
        migrations.CreateModel(
            name='DestructionCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=80)),
                ('title_at_destruction', models.CharField(max_length=255)),
                ('content_hash', models.CharField(blank=True, default='', help_text='Hash of the last version — proof of what was destroyed', max_length=64)),
                ('reason', models.CharField(blank=True, default='', max_length=255)),
                ('certified_at', models.DateTimeField(auto_now_add=True)),
                ('certified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destruction_certificates', to='documents.document')),
            ],
        ),
        migrations.CreateModel(
            name='OfflinePackGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device', models.CharField(blank=True, default='', max_length=128)),
                ('status', models.CharField(choices=[('active', 'Active'), ('revoked', 'Revoked (wipe on next sync)'), ('wiped', 'Wiped')], default='active', max_length=12)),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('synced_at', models.DateTimeField(blank=True, help_text='Last device sync that acknowledged status', null=True)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offline_grants', to='meetings.meeting')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offline_grants', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-granted_at',),
            },
        ),
    ]
