# Generated by Django 5.1.4 on 2026-07-17 16:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entities', '0003_entitysettings'),
        ('meetings', '0004_meeting_quorum_attendance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InterestDeclaration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('directorship', 'Directorship elsewhere'), ('shareholding', 'Shareholding'), ('contract', 'Interest in a contract'), ('other', 'Other')], max_length=16)),
                ('party', models.CharField(help_text='The company/counterparty the interest is in', max_length=255)),
                ('details', models.TextField(blank=True, default='')),
                ('declared_on', models.DateField()),
                ('withdrawn_on', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('director', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interest_declarations', to=settings.AUTH_USER_MODEL)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='interest_declarations', to='entities.entity')),
            ],
            options={
                'ordering': ('-declared_on', 'party'),
            },
        ),
        migrations.CreateModel(
            name='ConflictDeclaration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True, default='')),
                ('declared_at', models.DateTimeField(auto_now_add=True)),
                ('agenda_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conflict_declarations', to='meetings.agendaitem')),
                ('director', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conflict_declarations', to=settings.AUTH_USER_MODEL)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conflict_declarations', to='meetings.meeting')),
                ('interest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conflicts', to='conflicts.interestdeclaration')),
            ],
            options={
                'ordering': ('-declared_at',),
                'unique_together': {('meeting', 'agenda_item', 'director')},
            },
        ),
    ]
